services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 443:443   # only need https port forwarded, due to current traefik setup
      - 8080:8080  # traefik drashboard port
    volumes:
      - ./:/etc/traefik/
      - ./secrets:/secrets
      - /var/log/crowdsec/:/var/log/crowdsec/
    networks:
      - proxy   # change to your docker network name
      - secure  # have a second one for sensitive containers
    labels:
      traefik.enable: true   # Enable Traefik reverse proxy
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.http.routers.api.middlewares: auth@file   # enabling authelia security to traefik
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
      PORKBUN_API_KEY_FILE: /secrets/PORKBUN_API_KEY
      PORKBUN_SECRET_API_KEY_FILE: /secrets/PORKBUN_SECRET_API_KEY
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - socket-proxy

  socket-proxy:
    container_name: traefik-socket-proxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      TZ: America/Vancouver
      CONTAINERS: 1
      POST: 0
      EVENTS: 1  # Grant access to the /events API for crowdsec v1.6.9
    privileged: true
    networks:
      - secure
    security_opt:
      - no-new-privileges:true
    restart: always

networks:
  proxy:
    external: true

  secure:
    external: true
