x-app: &default
  restart: unless-stopped
  networks:
    -  proxy
  environment:
    TZ: America/Vancouver
    PGID: ${PGID:?err}
    PUID: ${PUID:?err}
    UMASK: ${UMASK:?err}
  labels: &labels
    traefik.enable: true
    com.centurylinklabs.watchtower.enable: true
  security_opt:
    - no-new-privileges:true

services:
  jellyfin:
    <<: *default
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin:/config:rw
      - ${MEDIA_DIR:?err}:/data/media:ro
      - ${TRANSCODE_DIR:?err}:/tmp/jellyfin:rw

  jellyseerr:
    <<: *default
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr:/app/config

networks:
  proxy:
    external: true
